#!/bin/zsh

setopt nullglob

die() {
  echo $*
  exit 1
}

typeset -A opts
zparseopts -D -A opts h: e: t: b:

if [[ $1 = t || $1 = transmission ]] ; then
  id=$(rkt list | grep sonkar | grep running | cut -f1)
  sudo rkt enter $id /bin/run-transmission.sh up
  exit
fi

openvpn_cfg=$1
[ -z $1 ] && die must provide openvpn config file

bindaddr=${opts[-b]:-0.0.0.0}
hosts=${opts[-h]}
exec=${opts[-e]}
torrentdir=${opts[-t]}

thisdir=$(dirname $0)
aci=$(echo $thisdir/../share/sonkar-*.aci)
if [[ ! -f "$aci" ]] ; then
  aci=$(echo $thisdir/sonkar-*.aci)
  [[ -f "$aci" ]] || die could not find aci
fi

if [ x$1 = xip ] ; then
  sudo rkt list | grep sonkar | grep running | sed 's/.*=//'
  exit 0
fi

cleanup() {
  [ -d $tmpdir ] && rm -r $tmpdir
}
trap cleanup EXIT TERM
tmpdir=$(mktemp -d)

cp $openvpn_cfg $tmpdir/cfg.ovpn || die could not copy ovpn config to $tmpdir
if [[ $hosts ]] ; then
  cp $hosts $tmpdir/hosts
else
  touch $tmpdir/hosts
fi

extra_args=()
if [ -n "$torrentdir" ]; then
  extra_args+=--volume
  extra_args+=torrentdir,kind=host,source=$torrentdir
  extra_args+=--mount
  extra_args+=volume=torrentdir,target=/var/torrents
fi

# sudo iptables -P FORWARD ACCEPT
sudo rkt run \
  --insecure-options=image,paths,capabilities \
  --dns=127.0.0.1 --net=default --interactive \
  --volume vpnconfig,kind=host,source=$tmpdir \
  --mount volume=vpnconfig,target=/var/vpn-config \
  --port=proxy:$bindaddr:1080 \
  --port=transmission:$bindaddr:9091 \
  $extra_args \
  $aci ${exec+--exec=$exec}
