#!/bin/zsh

setopt nullglob

die() {
  echo $*
  exit 1
}

typeset -A opts
zparseopts -D -A opts h: e:

openvpn_cfg=$1
[ -z $1 ] && die must provide openvpn config file

hosts=${opts[-h]}
exec=${opts[-e]}

thisdir=$(dirname $0)
aci=$(echo $thisdir/../share/sonkar-*.aci)
if [[ ! -f "$aci" ]] ; then
  aci=$(echo $thisdir/sonkar-*.aci)
  [[ -f "$aci" ]] || die could not find aci
fi

if [ x$1 = xip ] ; then
  sudo rkt list | grep sonkar | grep running | sed 's/.*=//'
  exit 0
fi

cleanup() {
  [ -d $tmpdir ] && rm -r $tmpdir
}
trap cleanup EXIT TERM
tmpdir=$(mktemp -d)

cp $openvpn_cfg $tmpdir/cfg.ovpn || die could not copy ovpn config to $tmpdir
if [[ $hosts ]] ; then
  cp $hosts $tmpdir/hosts
else
  touch $tmpdir/hosts
fi

# sudo iptables -P FORWARD ACCEPT
sudo rkt run \
  --insecure-options=image,paths,capabilities \
  --dns=127.0.0.1 --net=default --interactive \
  --volume vpnconfig,kind=host,source=$tmpdir \
  --mount volume=vpnconfig,target=/var/vpn-config \
  --port=proxy:1080 \
  $aci ${exec+--exec=$exec}
