#!/bin/zsh

setopt nullglob

# dns=8.8.8.8
dns=127.0.0.1

die() {
  echo $*
  exit 1
}

thisdir=$(dirname $0)
aci=$(echo $thisdir/../share/sonkar-*.aci)
if [[ ! -f "$aci" ]] ; then
  aci=$(echo $thisdir/sonkar-*.aci)
  [[ -f "$aci" ]] || die could not find aci
fi

if [ x$1 = xip ] ; then
  sudo rkt list | grep sonkar | grep running | sed 's/.*=//'
  exit 0
fi

[ $# -eq 0 ] && die must provide ovpn file
tmpdir=$(mktemp -d)

finish() {
  [ -d $tmpdir ] && rm -r $tmpdir
}
trap finish EXIT TERM

cp $1 $tmpdir/cfg.ovpn || die could not copy ovpn config to $tmpdir
shift

# sudo iptables -P FORWARD ACCEPT
sudo rkt run \
  --insecure-options=image,paths,capabilities \
  --dns=$dns --net=default --interactive \
  --volume vpnconfig,kind=host,source=$tmpdir \
  --mount volume=vpnconfig,target=/var/vpn-config \
  --port=proxy:1080 \
  $aci $*
